// Re-export Wails auto-generated bindings for the App struct
// These bindings are generated by `wails generate` and provide type-safe
// communication between the Vue frontend and Go backend
export { GetVersion, Greet } from '../../wailsjs/go/main/App'
